##################### IMPORTANT ###############################
## DON'T USE THIS EXAMPLE FILE SINCE IT FAKES A STACKMATCH
## There are actually real stackmatch implementations available
##################### IMPORTANT ###############################

[nats]
broker-url = "nats-server"
broker-port = 4222

[switch]
name = "40m_ant_switch"
type = "dummy_switch"

[40m_ant_switch]
name = "Antenna Switch 40m" # name of the stackmatch
index = 5 # order (helper for consistent visualization)
exclusive = true
ports = ["sw"]

[sw]
name = "SW"
index = 0
exclusive = true
terminals = ["sw_port1", "sw_port2", "sw_port3", "sw_port4"]

# Terminal (corresponds to the buttons you would see in the UI)
[sw_port1]
name = "3L"
index = 1 #order

# Terminal
[sw_port2]
name = "2/2 NA"
index = 2

# Terminal
[sw_port3]
name = "DIPOL"
index = 3

[sw_port4]
name = "DUMMY"
index = 4
